version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      size-limit:
        patterns:
          - 'size-limit'
          - '@size-limit/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'eslint-*'
          - 'typescript-eslint'
      playwright:
        patterns:
          - 'playwright'
          - '@playwright/*'
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint-plugin-vitest'
        update-types: ['version-update:semver-major']
      - dependency-name: '@eslint/js'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
